version: '3.2'
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: '{SA_PASSWORD}'
      ACCEPT_EULA: '{ACCEPT_EULA}'